var NAVTREEINDEX0 = {
'../../doc/doxy/annotated.html':[10, 1],
'../../doc/doxy/files.html':[10, 0],
'../../doc/doxy/functions.html':[10, 3],
'../../doc/doxy/globals.html':[10, 5],
'../../doc/doxy/hierarchy.html':[10, 2],
'../../doc/doxy/namespacemembers.html':[10, 6],
'../../doc/doxy/namespaces.html':[10, 4],
'App.html':[2, 0, 0],
'App.ned.html':[9, 0],
'BurstyApp.html':[2, 0, 1],
'BurstyApp.ned.html':[9, 1],
'IApp.html':[2, 0, 2],
'IApp.ned.html':[9, 2],
'L2Queue.html':[2, 0, 3],
'L2Queue.ned.html':[9, 3],
'Node.html':[2, 0, 5],
'Node.ned.html':[9, 5],
'Packet.html':[7, 0, 0],
'Packet.msg.html':[9, 6],
'RandomGraph.html':[2, 0, 6],
'RandomGraph.ned.html':[9, 7],
'Routing.html':[2, 0, 7],
'Routing.ned.html':[9, 8],
'full-msg-inheritance-diagram.html':[1, 3],
'full-msg-usage-diagram.html':[1, 2],
'full-ned-inheritance-diagram.html':[1, 1],
'full-ned-usage-diagram.html':[1, 0],
'index.html':[0],
'namespaces.html':[7],
'namespaces.html#default':[7, 0],
'ned.DatarateChannel.html':[2, 1, 0],
'ned.DelayChannel.html':[2, 1, 1],
'ned.IBidirectionalChannel.html':[2, 1, 2],
'ned.IUnidirectionalChannel.html':[2, 1, 4],
'ned.IdealChannel.html':[2, 1, 3],
'networkTopoInfo.html':[2, 0, 4],
'networkTopoInfo.ned.html':[9, 4],
'packages.html':[2],
'packages.html#default':[2, 0],
'packages.html#ned':[2, 1],
};